### ISSUE TITLE
如何在项目中设置不同的 log Store

### ISSUE THREAD

**Issue by JeaNile** [seffeng/laravel-sls#1]

**Comment by seffeng** [comment]
抱歉，暂时不支持配置，1.0.3可通过 先执行 app('sls')->setLogStore('new-logStore') 实现。

**Comment by JeaNile** [comment]
好吧，那只能先设置 log Store 再切换回去这么操作了

**Comment by seffeng** [comment]
2.0 支持多 store 配置。可通过日志配置文件 logging.php 配置 store，通过 Log::channel('channel') 实现写入不同的 project 和 logStore 。需要使用新的 sls.php 配置结构。具体请参考 README.md 和 CHANGELOG.md。
